name: Manual trigger to build and upload to pages

on:
  # Runs when manually triggered using the UI or API.
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Greet
      run: echo "Hello ${{ github.event.inputs.name }}"

    # Code checkout is not automatic
    - name: Checkout
      uses: actions/checkout@v2
 
    - name: Install
      #run: sudo apt-get -y install $(grep "^[^#]" dependencies.txt)
      run: pip install tqdm

    - name: Build
      env:
        SITEMAP_URL: https://abitrolly.github.io/fedora-packages-static/
      run: make all

    - name: Upload to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.2.0
      with:
        # Git branch where assets will be deployed
        #target_branch: # optional, default is gh-pages
        # Create incremental commit instead of doing push force
        keep_history: true # optional, default is false
        # Allow an empty commit to be created
        #allow_empty_commit: # optional, default is true
        # Build directory to deploy
        build_dir: public_html
        # The committer name and email address
        #committer: # optional
        # The author name and email address
        #author: # optional
        # Commit message
        #commit_message: # optional
        # Write the given domain name to the CNAME file
        #fqdn: # optional
        # Allow Jekyll to build your site
        jekyll: false # optional, default is true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
